@WebApiLab.Api_HostAddress = http://localhost:5181

GET {{WebApiLab.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApiLab.Api_HostAddress}}/math?a=2&b=3
Accept: application/json

###
